//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TourMaster.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MainSliderImage
    {
        public int Id { get; set; }
        public string ImageURL { get; set; }
        public int OriginId { get; set; }
    
        public virtual Origin Origin { get; set; }
    }
}
