//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TourMaster.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Origin
    {
        public int Id { get; set; }
        public string Logo { get; set; }
        public string Title { get; set; }
        public string MainSliderPhotos { get; set; }
        public string About { get; set; }
        public string JoinUs { get; set; }
        public string Facebook { get; set; }
        public string Instagram { get; set; }
        public string Twitter { get; set; }
        public string GooglePlus { get; set; }
        public string Youtube { get; set; }
        public string Copyright { get; set; }
    }
}
